services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: start-base:latest
    ports:
      - "8080:5600"
    environment:
      - DATABASE_URL=sqlite:////app/data/db/start_base.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
