"""add col_span row_span to site

Revision ID: 57aa45b9d509
Revises: eba4772233e7
Create Date: 2026-08-21 22:22:04.944703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57aa45b9d509'
down_revision: Union[str, Sequence[str], None] = 'eba4772233e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('col_span', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('row_span', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('row_span')
        batch_op.drop_column('col_span')

    # ### end Alembic commands ###
