"""add allow_lan and plugin_meta to site

Revision ID: 955fb4f956c7
Revises: 7a1e2f3d4c5b
Create Date: 2026-08-24 19:58:40.452451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '955fb4f956c7'
down_revision: Union[str, Sequence[str], None] = '7a1e2f3d4c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_lan', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('plugin_meta', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('plugin_meta')
        batch_op.drop_column('allow_lan')

    # ### end Alembic commands ###
